ArrayIndexOutOfBoundsException: 2 #38 NullPointerException #39 [Bug][Gameplay] - Guides error #35
- Deprecated tags will now show warnings instead of errors

Signed-off-by: Daniel Ricci <thedanny09@gmail.com>